const restful = require('node-restful');

const { mongoose } = restful;

const candidatoSchema = new mongoose.Schema({
  tipoServico: { type: String, maxlength: 1, required: true },
  agenteFinanceiro: { type: Number, maxlength: 999999999999999999999999999999, required: true },
  codigoInscricao: { type: Number, max: 999999999999999999999999999999, required: true },
  cpfCandidato: { type: String, maxlength: 11, required: true },
  nomeCandidato: { type: String, maxlength: 100, required: true },
  dataDeNascimento: { type: String, maxlength: 8, required: true },
  sexoCandidato: { type: String, maxlength: 1, required: true },
  naturalDe: { type: String, maxlength: 30, required: true },
  ufNaturalidade: { type: String, maxlength: 2, required: true },
  paisDeNascimento: { type: String, maxlength: 15, required: true },
  rg: { type: String, maxlength: 10, required: true },
  orgaoEmissor: { type: String, maxlength: 15, required: true },
  dataEmissaoRG: { type: String, maxlength: 8, required: true },
  telefoneCelular: { type: Number, maxlength: 99999999999, required: true },
  email: { type: String, maxlength: 40, required: true },
  endereco: { type: String, maxlength: 100, required: true },
  tipoDeLogradouro: { type: String, maxlength: 72, required: true },
  logradouro: { type: String, maxlength: 45, required: true },
  numero: { type: Number, max: 99999, required: true },
  complemento: { type: String, maxlength: 100, required: true },
  bairro: { type: String, maxlength: 20, required: true },
  cep: { type: String, maxlength: 8, required: true },
  cidade: { type: String, maxlength: 30, required: true },
  estado: { type: String, maxlength: 2, required: true },
  telefone1: { type: Number, max: 9999999999, required: true },
  estadoCivil: { type: String, maxlength: 20, required: true },
  nomeConjuge: { type: String, maxlength: 100, required: true },
  cpfConjuge: { type: String, maxlength: 11, required: true },
  trabalhaOuNao: { type: String, maxlength: 1, required: true },
  tipoTrabalho: { type: String, maxlength: 100, required: true },
  quantoTempoTrabalho: { type: Number, max: 99, required: true },
  rendaPessoal: { type: Number, max: 99999999999999999, required: true },
  rendaFamiliar: { type: Number, max: 99999999999999999, required: true },
  enemNota: { type: Number, max: 99999, required: true },
  enemAno: { type: Number, max: 9999, required: true },
  vezesPrestouEnem: { type: Number, max: 99, required: true },
  escolaCursouEnsinoMedio: { type: String, maxlength: 100, required: true },
  quantosMoramComCandidato: { type: Number, max: 99, required: true },
  quantidadeDependentesCandidato: { type: Number, max: 99, required: true },
  nomePai: { type: String, maxlength: 100, required: true },
  cpfPai: { type: Number, max: 99999999999, required: true },
  ocupacaoPai: { type: String, maxlength: 100, required: true },
  escolaridadePai: { type: String, maxlength: 100, required: true },
  enderecoPai: { type: String, maxlength: 100, required: true },
  nomeMae: { type: String, maxlength: 100, required: true },
  cpfMae: { type: Number, max: 99999999999, required: true },
  ocupacaoMae: { type: String, maxlength: 100, required: true },
  escolaridadeMae: { type: String, maxlength: 100, required: true },
  enderecoMae: { type: String, maxlength: 100, required: true },
});

module.exports = restful.model('Candidato', candidatoSchema);
